#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

xset +fp /usr/share/fonts/local
xset fp rehash
#setxkbmap -layout pt
setxkbmap -layout pt,us -variant ,intl -option grp:shifts_toggle
xsetroot -cursor_name left_ptr
#feh --bg-center ~/Images/wall_archlinux.png
feh --bg-fill ~/Images/numix.png
#wmname LG3D

#exec startxfce4

compton &
#sxhkd &
#2> ~/.bspwm.log &

#wicd-client -t &
numlockx &
redshift-gtk -l 40.2:-8.4 &
nm-applet &
QT_STYLE_OVERRIDE=gtk dropbox &
#caffeine &

exec i3
#exec dbus-launch bspwm -s "$PANEL_FIFO" -p W
#exec openbox-session

